name: release
on:
  push:
    tags:
      - 'v*'
      - '!v*-alpha*'
      - '!v*-beta*'
      - '!v*-streamer*'
      - '!v*-rc*'
      
jobs:
  build-livery-package:
    # Prevent running this on forks
    if: github.repository_owner == 'Horizon-Simulations'
    name: 'Build HS78X Livery Package'
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      ZIP_NAME: hs78X-livery-package-release.zip
      BUILD_DIR_NAME: release
      CLOUDFLARE_WORKER_PASSWORD: ${{ secrets.CLOUDFLARE_WORKER_PASSWORD }}
      CDN_BUCKET_DESTINATION: addons/hs78X-livery-package/release
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: false
          haskell: false
          large-packages: true
          docker-images: false
          swap-storage: false
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo A32NX_PRODUCTION_BUILD=1 >> .env
          echo CLIENT_ID=${{ secrets.NAVIGRAPH_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.NAVIGRAPH_CLIENT_SECRET }} >> .env
          echo CHARTFOX_SECRET=${{ secrets.CHARTFOX_SECRET }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
      - name: Setup Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Build Livery Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/build-hs78X-liveries.sh --no-tty -j 4
          docker system prune -af
          rm -rf ./hs-78X-liveries/src
      - name: Build ZIP files
        run: |
          node ./scripts/fragment-hs78X-liveries.js
          cp ./hs-78X-liveries/out/build-modules/modules.json ./hs-78X-liveries/out/horizonsim-aircraft-787-10-livery-package/install.json
          node ./scripts/install-source-hs78X-liveries.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./hs-78X-liveries/out/
          zip -r ../../${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME }} ./horizonsim-aircraft-787-10-livery-package/
          cd ../../
      - name: Upload to CloudFlare CDN
        run: |
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./hs-78X-liveries/out/build-modules
      - name: Upload Release Config to CloudFlare CDN
        run: |
          mkdir -p ./hs-78X-liveries/out/config
          echo "releases:" >> ./hs-78X-liveries/out/config/releases.yaml
          echo "  - name: $GITHUB_REF_NAME" >> ./hs-78X-liveries/out/config/releases.yaml
          echo "    date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> ./hs-78X-liveries/out/config/releases.yaml
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./hs-78X-liveries/out/config